import type { CrmLabels } from "./_types";

// Default es-AR copy for the CRM-lite surfaces. Shared across verticals so a
// new vertical only declares its stages: `crm: { stages, …, labels: CRM_LABELS_ES }`
// (spread and override single keys when a vertical needs different wording).
export const CRM_LABELS_ES: CrmLabels = {
  nav: "Leads",
  pageKicker: "Gestión comercial",
  pageTitle: "Leads",
  viewList: "Lista",
  viewBoard: "Tablero",
  searchPlaceholder: "Buscar por nombre o teléfono",
  filterAllStages: "Todas las etapas",
  filterAllOwners: "Todos los responsables",
  filterMine: "Mis leads",
  filterAtRisk: "Se pierden pronto",
  filterOverdue: "Vencidos",
  filterUnassigned: "Sin responsable",
  columnContact: "Contacto",
  columnStage: "Etapa",
  columnOwner: "Responsable",
  columnLastActivity: "Última actividad",
  columnNextStep: "Próximo paso",
  cardTitle: "Seguimiento comercial",
  stageLabel: "Etapa",
  ownerLabel: "Responsable",
  nextStepLabel: "Próximo paso",
  unassigned: "Sin asignar",
  takeLead: "Tomar",
  takenToast: "Es tuyo",
  ownerLockedHint: "Solo un admin puede reasignar este lead.",
  moveTo: "Mover a…",
  setReminder: "Guardar recordatorio",
  reminderNotePlaceholder: "Ej.: llamar para coordinar la visita",
  markDone: "Hecho",
  addActivity: "Guardar",
  addActivityTemplate: "Guardar {kind}",
  activityKindLabel: "Tipo de actividad",
  activityPlaceholders: {
    note: "¿Qué pasó? Ej.: le envié 3 opciones en Palermo",
    call: "¿Qué hablaron? Ej.: quiere ver el PH el sábado",
    visit: "¿Cómo fue la visita? Ej.: le gustó el balcón, duda por el precio",
    meeting: "¿Qué se acordó? Ej.: trae la reserva el lunes",
  },
  shortcutHintTemplate: "{keys} para guardar",
  moveToStageOfferTemplate: "Pasar a {stage}",
  activityTitle: "Actividad",
  remindersTitle: "Recordatorios",
  qualificationTitle: "Lo que captó el bot",
  emptyLeads: "No hay leads para este filtro.",
  emptyActivity: "Todavía no hay actividad registrada.",
  emptyColumn: "Sin leads",
  save: "Guardar",
  cancel: "Cancelar",
  saved: "Guardado",
  whenLabel: "Cuándo",
  autoStageHint: "La puso el bot. Si ya hablaste con la persona, movelo a mano.",
  autoStageDetail:
    "Etapa automática según la conversación. Las respuestas enviadas desde el teléfono (fuera del panel) no se detectan: movelo a mano si ya lo contactaste.",
  lostSinceTemplate: "Perdido desde el {date} · {reason}",
  atRiskTemplate: "Se pierde el {date}",
  daysInactiveTemplate: "{days} días sin actividad",
  bannerAtRiskTemplate: "{n} leads pasan a perdido en los próximos días",
  bannerAtRiskOne: "1 lead pasa a perdido en los próximos días",
  bannerOverdueTemplate: "{n} recordatorios vencidos",
  bannerOverdueOne: "1 recordatorio vencido",
  reminderOverdueTemplate: "Vencido · {date}",
  reminderUpcomingTemplate: "{date}",
  lostReasonLabel: "Motivo",
  lostReasons: [
    "Compró o alquiló con otro",
    "Fuera de presupuesto",
    "No responde",
    "Ya no busca",
    "Otro",
  ],
  lostReasonAuto: {
    opt_out: "pidió no recibir más mensajes",
    inactivity: "sin actividad",
  },
  eventKinds: {
    note: "Nota",
    call: "Llamada",
    visit: "Visita",
    meeting: "Reunión",
    stage_change: "Cambio de etapa",
    assignment: "Asignación",
    reminder_set: "Recordatorio",
    reminder_done: "Recordatorio cumplido",
    contact: "Respuesta desde el panel",
    created: "Cargado a mano",
    priority: "Prioridad",
    budget: "Presupuesto",
    opened: "Oportunidad abierta",
    kind_change: "Rubro",
  },
  errors: {
    already_owned: "Otra persona tomó este lead recién.",
    already_exists: "Ese teléfono ya es un lead.",
    invalid_phone: "Revisá el teléfono: poné el código de área y el número.",
    invalid_source: "Elegí un origen de la lista.",
    invalid_intent: "Elegí una intención de la lista.",
    invalid_kind: "Elegí un rubro de la lista.",
    person_not_found: "Ese contacto no existe en el panel.",
    opted_out: "Esta persona pidió no recibir más mensajes.",
    invalid_stage: "Esa etapa no existe para este panel.",
    invalid_priority: "Esa prioridad no existe.",
    invalid_currency: "Elegí una moneda de la lista.",
    invalid_budget: "Poné un monto entero mayor a cero.",
    invalid_owner: "Ese responsable no tiene acceso al panel.",
    invalid_body: "Revisá los datos e intentá de nuevo.",
    forbidden: "Tu usuario no puede modificar leads.",
    not_found: "Esta función no está habilitada.",
    network: "No se pudo guardar. Revisá la conexión e intentá de nuevo.",
  },

  columnBudget: "Presupuesto",
  columnSource: "Origen",
  sourceWhatsapp: "WhatsApp",
  daysInStageTemplate: "{days} d en la etapa",
  daysInStageToday: "Entró hoy a la etapa",

  viewActivity: "Actividad",
  filterAllKinds: "Todos los tipos",
  filterAllPeople: "Todas las personas",

  newLead: "Nuevo lead",
  newLeadTitle: "Cargar un lead",
  newLeadHint:
    "Para consultas que no llegaron por WhatsApp. Si después escribe al bot, la conversación se suma a este mismo lead.",
  nameLabel: "Nombre",
  phoneLabel: "Teléfono",
  phonePlaceholder: "11 5555-0000",
  phonePreviewTemplate: "Se guarda como {phone}",
  sourceLabel: "Origen",
  noteLabel: "Nota (opcional)",
  createLead: "Cargar lead",
  leadCreated: "Lead cargado",
  openExisting: "Abrir el existente",
  noConversationTitle: "Todavía no escribió por WhatsApp",
  noConversationBody:
    "Este lead se cargó a mano. Cuando escriba al bot, la conversación aparece acá.",
  openWhatsapp: "Abrir en WhatsApp",
  manualOriginTemplate: "Cargado a mano · {source}",
  manualByTemplate: "por {who} el {date}",

  priority: {
    label: "Prioridad",
    none: "Sin prioridad",
    names: { alta: "Alta", media: "Media", baja: "Baja" },
    filterLabel: "Prioridad",
  },

  summary: {
    view: "Resumen",
    windowTemplate: "Últimos {days} días",
    closed: "Cerrados",
    active: "Trabajados",
    new: "Nuevos",
    dueSoon: "Vencen pronto",
    overdueCaptionTemplate: "{n} vencidos",
    overdueCaptionOne: "1 vencido",
    noOverdueCaption: "Sin vencidos",
    stagesTitle: "Etapas",
    stagesDescription: "Leads por etapa, incluidos los perdidos.",
    priorityTitle: "Prioridad",
    priorityDescription: "Leads abiertos según la prioridad que les puso el equipo.",
    workloadTitle: "Carga del equipo",
    workloadDescription: "Leads abiertos por responsable.",
    sourcesTitle: "Origen",
    sourcesDescription: "Por dónde llegó cada lead.",
    totalUnit: "leads",
    empty: "Todavía no hay leads para resumir.",
  },

  budget: {
    label: "Presupuesto",
    none: "Sin presupuesto",
    amountLabel: "Monto",
    currencyLabel: "Moneda",
    amountPlaceholder: "Ej.: 150000",
    save: "Guardar",
    clear: "Quitar",
    clearHint: "Vuelve a mostrar el que captó el bot, si lo hay.",
    fromBot: "Captado por el bot",
  },

  clearFilters: "Limpiar filtros",
  intentLabel: "Intención",
  filterAllIntents: "Todas las intenciones",
  intentNone: "Sin intención",

  reminderOverdueRelativeTemplate: "Vencido {relative}",
  reminderDueRelativeTemplate: "Vence {relative}",
  reminderChange: "Cambiar",
  reminderPresets: {
    tomorrow: "Mañana",
    in3days: "En 3 días",
    nextWeek: "Próxima semana",
    custom: "Elegir fecha",
  },
  dateLabel: "Fecha",
  timeLabel: "Hora",

  showAllTemplate: "Ver todo ({n})",
  showLess: "Ver menos",

  opportunity: {
    listTitle: "Oportunidades",
    newButton: "Nueva oportunidad",
    dialogTitle: "Nueva oportunidad",
    dialogHint:
      "Para cuando la misma persona consulta por otra cosa: un alquiler y una venta se siguen por separado.",
    kindLabel: "Rubro",
    kindNone: "Sin rubro",
    titleLabel: "Título (opcional)",
    titlePlaceholder: "Ej.: 2 ambientes en Palermo",
    create: "Abrir oportunidad",
    createdToast: "Oportunidad abierta",
    ofTotalTemplate: "{n} de {total}",
    ordinalTemplate: "{n}ª",
    openedTemplate: "Abierta el {date}",
    closedTemplate: "Cerrada el {date}",
    openedByBot: "La abrió el bot al derivar la consulta.",
    newIntentTemplate: "Consulta nueva: {kind}",
    openFromIntent: "Abrir oportunidad",
    underivedTitle: "Sin derivar",
    underivedCountTemplate: "{n} sin derivar esta semana",
    underivedCountOne: "1 sin derivar esta semana",
    underivedHint:
      "Escribieron al bot pero no llegaron a derivar. Abrí una oportunidad si la consulta vale la pena.",
    underivedEmpty: "Todas las consultas de esta semana llegaron a derivar.",
    allConversations: "Todas",
    groupByContact: "Agrupar por contacto",
    oneOpportunity: "1 oportunidad",
    manyOpportunities: "{n} oportunidades",
  },

  openConversation: "Ver conversación",
  close: "Cerrar",

  editFieldTemplate: "Editar {field}",
  addValue: "Agregar…",
  confirm: "Confirmar",

  filterToday: "Hoy",
  filterGroupMine: "Para mí",
  filterGroupUrgency: "Urgencia",
  moreInListTemplate: "+{n} en la lista",
  attentionOverdueTemplate: "Vencido {relative}",
  attentionTodayTemplate: "Vence hoy, {time}",
  attentionAtRiskTemplate: "Se pierde el {date}",
  attentionUpcomingTemplate: "Vence {relative}",
  expandColumnTemplate: "Ver {stage}",
  collapseColumn: "Plegar",
  undo: "Deshacer",
  markLost: "Marcar perdido",
  markLostTitleTemplate: "Marcar perdido: {name}",
  movedToastTemplate: "{name} → {stage}",
  assignedToastTemplate: "{name} → {owner}",
  priorityToastTemplate: "{name} · {priority}",
  emptyFiltered: "Ningún lead coincide con estos filtros.",
  emptyFirstRun: "Todavía no hay leads. Llegan solos cuando alguien escribe al bot, o cargá uno con «Nuevo lead».",

  guide: {
    view: "Guía",
    title: "Cómo funciona el seguimiento",
    intro:
      "Cada lead está en una sola etapa. Algunas las mueve el bot según la conversación; otras las marca un asesor desde el panel. Esta guía explica cada una y las reglas que aplican solas.",
    stagesTitle: "Etapas",
    moverBot: "La mueve el bot",
    moverPerson: "La marca un asesor",
    moverBoth: "El bot o un asesor",
    autoNew: "Cuando la persona escribe por primera vez, o cuando se carga a mano.",
    autoContacted: "Cuando alguien del equipo le responde desde el panel.",
    autoQualified: "Cuando el bot deriva la consulta al equipo.",
    autoLostTemplate:
      "Cuando pide no recibir más mensajes, o tras {days} días sin actividad. Un asesor también puede marcarla, con un motivo.",
    manualOnlyNote: "Solo a mano: el bot nunca la asigna.",
    rulesTitle: "Reglas automáticas",
    inactivityRuleTemplate:
      "Un lead sin actividad durante {days} días pasa a {lost} solo. {warn} días antes aparece como «Por vencer» en el tablero y en el aviso de arriba.",
    inactivityReversible:
      "Si la persona vuelve a escribir, o registrás una actividad o lo movés de etapa, sale de {lost} y retoma su seguimiento.",
    activityTitle: "Qué cuenta como actividad",
    activityIntro: "Cualquiera de estas cosas reinicia el reloj de inactividad:",
    activityMessages: "Un mensaje de WhatsApp, entrante o saliente",
    remindersTitle: "Recordatorios",
    remindersBody:
      "Desde la ficha del lead podés dejar un próximo paso con fecha. Los vencidos aparecen en Seguimiento y en el aviso de arriba; asignar un responsable o programar un recordatorio no cuenta como actividad.",
    priorityTitle: "Prioridad",
    priorityBody:
      "Es una marca que pone el equipo, nunca el bot. Los leads con prioridad aparecen primero en su columna y se pueden filtrar.",
    priorityMeaning: {
      alta: "Atender hoy: hay una oportunidad concreta o una urgencia.",
      media: "Seguir esta semana.",
      baja: "Sin apuro; se retoma cuando haya tiempo.",
    },
    sourcesTitle: "Origen",
    sourcesBody:
      "Los leads que escriben al bot llegan por WhatsApp. Los que llaman, visitan la oficina o vienen por un portal o un referido se cargan a mano con «Nuevo lead»; si después escriben, la conversación se suma al mismo lead.",
    opportunitiesTitle: "Una persona, varias oportunidades",
    opportunitiesIntro:
      "Cada tarjeta del tablero es una oportunidad: una consulta concreta, con su rubro, su etapa y su responsable. La misma persona puede tener varias a lo largo del tiempo — alquiló el año pasado y hoy pregunta por una venta — y cada una se sigue por separado. En la ficha del contacto están todas, numeradas por orden de apertura.",
    opportunitiesHandoff:
      "Cuando el bot deriva una consulta de un rubro que la persona no tiene abierto, se abre una oportunidad sola, en Calificado.",
    opportunitiesSameKind:
      "Si deriva otra vez por el mismo rubro, cuenta para la que ya está abierta: no se duplica.",
    opportunitiesMessages:
      "Los mensajes sueltos no abren nada. Mantienen viva la oportunidad y, si la persona pregunta por otro rubro, la tarjeta avisa «Consulta nueva» con un botón para abrirla vos.",
    opportunitiesManual:
      "También podés abrir una a mano desde la ficha del contacto, o con «Nuevo lead» para alguien que no vino por WhatsApp.",
    opportunitiesUnderived:
      "Quien escribió pero nunca llegó a derivar no ocupa lugar en el tablero: está en Conversaciones, con el filtro «Sin derivar», y arriba del tablero ves cuántos llegaron esta semana.",
  },
};
