import type { CrmLabels } from "./_types";

// Default es-AR copy for the CRM-lite surfaces. Shared across verticals so a
// new vertical only declares its stages: `crm: { stages, …, labels: CRM_LABELS_ES }`
// (spread and override single keys when a vertical needs different wording).
export const CRM_LABELS_ES: CrmLabels = {
  nav: "Leads",
  pageKicker: "Gestión comercial",
  pageTitle: "Leads",
  viewList: "Lista",
  viewBoard: "Tablero",
  searchPlaceholder: "Buscar por nombre o teléfono",
  filterAllStages: "Todas las etapas",
  filterAllOwners: "Todos los responsables",
  filterMine: "Mis leads",
  filterAtRisk: "Por vencer",
  filterOverdue: "Recordatorios vencidos",
  filterUnassigned: "Sin responsable",
  columnContact: "Contacto",
  columnStage: "Etapa",
  columnOwner: "Responsable",
  columnLastActivity: "Última actividad",
  columnNextStep: "Próximo paso",
  cardTitle: "Seguimiento comercial",
  stageLabel: "Etapa",
  ownerLabel: "Responsable",
  nextStepLabel: "Próximo paso",
  unassigned: "Sin asignar",
  takeLead: "Tomar",
  takeLeadConfirm: "¿Tomar este lead?",
  moveTo: "Mover a…",
  setReminder: "Guardar recordatorio",
  reminderNotePlaceholder: "Ej.: llamar para coordinar la visita",
  markDone: "Hecho",
  addActivity: "Registrar",
  activityPlaceholder: "¿Qué pasó? Ej.: le envié 3 opciones en Palermo",
  activityTitle: "Actividad",
  remindersTitle: "Recordatorios",
  qualificationTitle: "Lo que captó el bot",
  emptyLeads: "No hay leads para este filtro.",
  emptyActivity: "Todavía no hay actividad registrada.",
  emptyColumn: "Sin leads",
  save: "Guardar",
  cancel: "Cancelar",
  saved: "Guardado",
  whenLabel: "Cuándo",
  autoStageHint:
    "Etapa automática según la conversación. Las respuestas enviadas desde el teléfono (fuera del panel) no se detectan: movelo a mano si ya lo contactaste.",
  lostSinceTemplate: "Perdido desde el {date} · {reason}",
  atRiskTemplate: "Pasa a perdido el {date}",
  daysInactiveTemplate: "{days} días sin actividad",
  bannerAtRiskTemplate: "{n} leads pasan a perdido en los próximos días",
  bannerAtRiskOne: "1 lead pasa a perdido en los próximos días",
  bannerOverdueTemplate: "{n} recordatorios vencidos",
  bannerOverdueOne: "1 recordatorio vencido",
  reminderOverdueTemplate: "Vencido · {date}",
  reminderUpcomingTemplate: "{date}",
  lostReasonLabel: "Motivo",
  lostReasons: [
    "Compró o alquiló con otro",
    "Fuera de presupuesto",
    "No responde",
    "Ya no busca",
    "Otro",
  ],
  lostReasonAuto: {
    opt_out: "pidió no recibir más mensajes",
    inactivity: "sin actividad",
  },
  eventKinds: {
    note: "Nota",
    call: "Llamada",
    visit: "Visita",
    meeting: "Reunión",
    stage_change: "Cambio de etapa",
    assignment: "Asignación",
    reminder_set: "Recordatorio",
    reminder_done: "Recordatorio cumplido",
    contact: "Respuesta desde el panel",
  },
  errors: {
    already_owned: "Otra persona tomó este lead recién. Actualizá la página.",
    invalid_stage: "Esa etapa no existe para este panel.",
    invalid_owner: "Ese responsable no tiene acceso al panel.",
    invalid_body: "Revisá los datos e intentá de nuevo.",
    forbidden: "Tu usuario no puede modificar leads.",
    not_found: "Esta función no está habilitada.",
    network: "No se pudo guardar. Revisá la conexión e intentá de nuevo.",
  },
};
