// Copy for Configuración › Equipo (admin chrome, not vertical-specific).
export const TEAM_LABELS = {
  kicker: "Administración",
  title: "Equipo",
  intro:
    "Quién entra al panel y con qué permisos. El nombre se muestra como responsable de los leads; el WhatsApp recibe los recordatorios.",
  backToSettings: "Configuración",
  settingsCardTitle: "Equipo y permisos",
  settingsCardBody: "Asesores, roles y WhatsApp para recordatorios",
  columnPerson: "Persona",
  columnRole: "Rol",
  columnWhatsapp: "WhatsApp",
  emailLabel: "Email",
  nameLabel: "Nombre",
  namePlaceholder: "Ej.: Ana Gómez",
  whatsappPlaceholder: "5491122334455",
  notifyLabel: "Recordatorios por WhatsApp",
  addTitle: "Agregar persona",
  add: "Agregar",
  save: "Guardar",
  saved: "Guardado",
  added: "Persona agregada",
  remove: "Quitar acceso",
  removeConfirm: "¿Quitar acceso?",
  removed: "Acceso quitado",
  you: "vos",
  roles: {
    admin: "Admin — todo, incluida Configuración",
    asesor: "Asesor — gestiona leads",
    viewer: "Lectura — solo mira",
  },
  roleShort: { admin: "Admin", asesor: "Asesor", viewer: "Lectura" },
  errors: {
    cannot_change_self: "No podés cambiar tu propio rol ni quitarte el acceso.",
    last_admin: "Tiene que quedar al menos un admin.",
    invalid_body: "Revisá el email y el WhatsApp (solo números, con código de país).",
    forbidden: "Solo un admin puede cambiar el equipo.",
    network: "No se pudo guardar. Revisá la conexión e intentá de nuevo.",
  } as Record<string, string>,
} as const;
